### ISSUE TITLE
Update display of unchanged files

### ISSUE THREAD

**Issue by mydea** [mainmatter/ember-asset-size-action#5]
Currently, it prints the files that have an unchanged filesize the same way, in a table. This makes the comment noisier than it needs to be, IMHO, so I wonder what you think about removing this from the comment.

Personally, I only really care about files that have been changed, and the list of files can become quite long (e.g. if using engines, every single unchanged engine file will be listed).

Thanks for the great work here!

**Comment by mansona** [comment]
I would be happy to add that as a config to say "don't show unchanged files" 🤔 but I think that for the default use case it is better to have an explicit comment to give confidence that `XYZ.file` hasn't changed by what I have done in a PR. Does that make sense?

**Comment by mydea** [comment]
Yeah, makes sense! I think having a configuration option for that would be awesome :+1:

**Comment by mansona** [comment]
I ended up wrapping all files in a `<details>` block in #48 since we now support changes in chunks and there can be a **lot** of chunks 🙈 

I am going to close this issue since it pretty much solves the problem with noise (as long as nobody expands the details block 😂) 

Let me know if you don't consider this fixed 👍
